apiVersion: v1
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - address:
            socket_address:
              protocol: TCP
              address: 0.0.0.0
              port_value: 9211
          filter_chains:
            - filters:
                name: envoy.http_connection_manager
                typed_config:
                  "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                  codec_type: auto
                  stat_prefix: ingress_http
                  route_config:
                    name: local_route
                    virtual_hosts:
                      - name: local_route
                        domains:
                          - "*"
                        routes:
                          - match:
                              prefix: "/"
                            route:
                              cluster: local_service
                  http_filters:
                    - name: envoy.router
                      typed_config: {}
        - address:
            socket_address:
              protocol: TCP
              address: 0.0.0.0
              port_value: 9001
          filter_chains:
            - filters:
                name: envoy.http_connection_manager
                typed_config:
                  "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                  codec_type: auto
                  stat_prefix: egress_http
                  route_config:
                    name: egress_routes
                    virtual_hosts:
                      - name: local_service
                        domains:
                          - "service-b*"
                        routes:
                          - match:
                              prefix: "/"
                              headers:
                                - name: ':authority'
                                  suffix_match: ':8080'
                            route:
                              cluster: local_service
                      - name: service_a
                        domains:
                          - "service-a*"
                        routes:
                          - match:
                              prefix: "/"
                              headers:
                                - name: ':authority'
                                  suffix_match: ':8080'
                            route:
                              cluster: service_a_8080
                      - name: service_c
                        domains:
                          - "service-c*"
                        routes:
                          - match:
                              prefix: "/"
                              headers:
                                - name: ':authority'
                                  suffix_match: ':8080'
                            route:
                              cluster: service_c_8080
                  http_filters:
                    - name: envoy.router
                      typed_config: {}
      clusters:
        - name: local_service
          connect_timeout: 0.250s
          type: strict_dns
          lb_policy: round_robin
          load_assignment:
            cluster_name: local_service
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 8080
        - name: service_a_8080
          connect_timeout: 0.250s
          type: strict_dns
          lb_policy: round_robin
          load_assignment:
            cluster_name: service_a
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: service-a
                          port_value: 8080
        - name: service_c_8080
          connect_timeout: 0.250s
          type: strict_dns
          lb_policy: round_robin
          load_assignment:
            cluster_name: service_c
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: service-c
                          port_value: 8080
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: envoy-config-service-b
---
kind: Service
apiVersion: v1
metadata:
  name: service-b
spec:
  selector:
    app: service-b
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  initContainers:
    - name: proxy-init
      image: tehusername/proxy-init:1.3
      env:
        - name: SERVICE_PORTS
          value: "8080"
        - name: GID
          value: "1337"
        - name: UID
          value: "1337"
        - name: PROXY_EGRESS_PORT
          value: "9001"
        - name: PROXY_INGRESS_PORT
          value: "9211"
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
        privileged: true
  containers:
    - name: service-b
      image: tehusername/sample-service:2.2
      ports:
        - containerPort: 8080
          name: endpoint
    - name: proxy
      image: envoyproxy/envoy:latest
      securityContext:
        runAsUser: 1337
      command: ['/usr/local/bin/envoy']
      args: ['-c', '/etc/envoy/envoy.yaml']
      ports:
        - containerPort: 9211
          name: ingress
        - containerPort: 9001
          name: egress
        - containerPort: 8001
          name: admin
      volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
  volumes:
    - name: envoy-config
      configMap:
        name: envoy-config-service-b
