apiVersion: v1
data:
  envoy.yaml: |
    node:
      id: 'id-service-a'
      cluster: 'cluster-service-a'
    dynamic_resources:
      cds_config:
        api_config_source:
          api_type: REST
          refresh_delay: 10s
          cluster_names:
            - cds_cluster
    static_resources:
      clusters:
        - name: cds_cluster
          connect_timeout: 0.250s
          type: strict_dns
          lb_policy: round_robin
          load_assignment:
            cluster_name: cds_cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: cds-server
                          port_value: 8080
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: envoy-config-service-a
---
kind: Service
apiVersion: v1
metadata:
  name: service-a
spec:
  selector:
    app: service-a
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  initContainers:
    - name: proxy-init
      image: tehusername/proxy-init:1.3
      env:
        - name: SERVICE_PORTS
          value: "8080"
        - name: GID
          value: "1337"
        - name: UID
          value: "1337"
        - name: PROXY_EGRESS_PORT
          value: "9001"
        - name: PROXY_INGRESS_PORT
          value: "9211"
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
        privileged: true
  containers:
    - name: service-a
      image: tehusername/sample-service:2.2
      ports:
        - containerPort: 8080
          name: endpoint
    - name: proxy
      image: envoyproxy/envoy:latest
      securityContext:
        runAsUser: 1337
      command: ['/usr/local/bin/envoy']
      args: ['-c', '/etc/envoy/envoy.yaml']
      ports:
        - containerPort: 9211
          name: ingress
        - containerPort: 9001
          name: egress
        - containerPort: 8001
          name: admin
      volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
  volumes:
    - name: envoy-config
      configMap:
        name: envoy-config-service-a
